version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: crudDeAdocao
    environment:
      POSTGRES_DB: crudDeAdocao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5423:5432"
    restart: always
